export const clothes = [
  {
    shirt_aid: 1,
    shirt_title: "Sureshot Chino Tan",
    shirt_price: "5200",
    shirt_image: "clothing-1.jpg",
    shirt_category: "Pants",
    shirt_is_active: true,
  },
  {
    shirt_aid: 2,
    shirt_title: "Flintlock Tee Dk Moss",
    shirt_price: "1250",
    shirt_image: "clothing-2.jpg",
    shirt_category: "T Shirt",
    shirt_is_active: true,
  },
  {
    shirt_aid: 3,
    shirt_title: "Joggins Pants Black",
    shirt_price: "1000",
    shirt_image: "clothing-3.jpg",
    shirt_category: "Pants",
    shirt_is_active: true,
  },
  {
    shirt_aid: 4,
    shirt_title: "Sureshot HT Flight Jogger Black/White",
    shirt_price: "1050",
    shirt_image: "clothing-4.jpg",
    shirt_category: "Pants",
    shirt_is_active: true,
  },
  {
    shirt_aid: 5,
    shirt_title: "Box Tee Black",
    shirt_price: "2400",
    shirt_image: "clothing-5.jpg",
    shirt_category: "T shirt",
    shirt_is_active: true,
  },
  {
    shirt_aid: 6,
    shirt_title: "Sureshot Chino Black",
    shirt_price: "4950",
    shirt_image: "clothing-6.jpg",
    shirt_category: "Pants",
    shirt_is_active: true,
  },
  {
    shirt_aid: 7,
    shirt_title: "Sureshot Jogger Black",
    shirt_price: "4950",
    shirt_image: "clothing-7.jpg",
    shirt_category: "Pants",
    shirt_is_active: true,
  },
  {
    shirt_aid: 8,
    shirt_title: "Flintlock Tee Black",
    shirt_price: "1850",
    shirt_image: "clothing-8.jpg",
    shirt_category: "T Shirt",
    shirt_is_active: true,
  },
  {
    shirt_aid: 9,
    shirt_title: "Sureshot Denim Jogger Dk Blue",
    shirt_price: "4650",
    shirt_image: "clothing-9.jpg",
    shirt_category: "Pants",
    shirt_is_active: true,
  },
  {
    shirt_aid: 10,
    shirt_title: "Sureshot Jogger Dk Camo",
    shirt_price: "3700",
    shirt_image: "clothing-10.jpg",
    shirt_category: "Pants",
    shirt_is_active: true,
  },
];
