export const newArrivalArray = [
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "1lorem ipsum dolor sit amet",
    slug: "1lorem-ipsum-dolor-sit-amet",
    price: "499.99",
    thumbnails: [
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
    ],
    sizes: [50, 52, 26, 25, 27],
    rating: 3,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "2lorem ipsum dolor sit amet",
    slug: "2lorem-ipsum-dolor-sit-amet",
    price: "149.99",
    thumbnails: [
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
    ],
    sizes: [50, 52, 26, 25, 27],
    rating: 5,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "3lorem ipsum dolor sit amet",
    slug: "3lorem-ipsum-dolor-sit-amet",
    price: "199.99",
    thumbnails: [
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
    ],
    sizes: [50, 52, 26, 25, 27],
    rating: 10,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "4lorem ipsum dolor sit amet",
    slug: "4lorem-ipsum-dolor-sit-amet",
    price: "1499.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [50, 52, 26, 25, 27],
    rating: 1,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "6lorem ipsum dolor sit amet",
    slug: "6lorem-ipsum-dolor-sit-amet",
    price: "1499423.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [50, 52, 26, 25, 27],
    rating: 2,
  },
];
